# -*- coding: utf-8 -*-
"""Module 4: Portfolio Project - Part 1 - Colin Tenaglia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lq9YZi9QBQUUDVsG0whDXA2CTUQUSzx5
"""

#Creating a definition called "print_item_cost"
def print_item_cost(item):
    total_cost = item["item_price"] * item["item_quantity"]
    # formatting printout according to specifications
    print(f"{item['item_name']} {item['item_quantity']} @ ${item['item_price']:.2f} = ${total_cost:.2f}")


if __name__ == "__main__":
    items = []  # Creating an empty list to store items

    # Item 1
    print("Item 1")
    item_name = input("Enter the item name: ") #initializing with input
    item_price = float(input("Enter the item price: ")) #specified as float
    item_quantity = int(input("Enter the item quantity: ")) #specified as integer
    item1 = {"item_name": item_name, "item_price": item_price, "item_quantity": item_quantity}
    items.append(item1)  # Adds item 1 to the list
    print()

    # Item 2
    print("Item 2")
    item_name = input("Enter the item name: ") #initializing with input
    item_price = float(input("Enter the item price: ")) #specified as float
    item_quantity = int(input("Enter the item quantity: ")) #specified as integer
    item2 = {"item_name": item_name, "item_price": item_price, "item_quantity": item_quantity}
    items.append(item2)  # Adds item 2 to the list
    print()

    # Total cost using 'for' loop
    print("\nTOTAL COST")
    for item in items:
        print_item_cost(item) #pulling definition back in
    total_cost = sum(item["item_price"] * item["item_quantity"] for item in items)
    print(f"Total: ${total_cost:.2f}")

